### ISSUE TITLE
Understanding parallel singer errro

### ISSUE THREAD

**Issue by mehakmadhura** [popgenmethods/SINGER#21]

**Comment by YunDeng98** [comment]
Hi @mehakmadhura I apologize for the late response, I remember seeing this issue during the conference but didn't get the time to review this carefully. What I would first recommend to do, is to switch to version 0.1.8 and if this occurs again, you can send me your output files and I will debug from there. Apologies for the trouble.

**Comment by mehakmadhura** [comment]
Hii @YunDeng98, thank you! I tried using ver8, but it did not work for me. It prints the following texts and then returns a series of errors.
Index vcf files
------------------

Block length: 1000000
------------------
Processing segment 0
Processing segment 0
Processing segment 0
Processing segment 0
Processing segment 0
Processing segment 0
Processing segment 0
Processing segment 0
Processing segment 0
Processing segment 0
Parameters:
Effective population size: 1000000.0
Mutation rate: 7e-09
Recombination to mutation ratio: 1
Block length: 1000000

Number of MCMC samples: 10
Thinning interval length: 20
Site flip probability: 0.5
Tskit conversion freq: 1
Number of cores: 20
Indexing VCF file: 

For me, I think ver 7 works better.
Thank you

**Comment by zhangming-m** [comment]
Have you solved this problem? I think my problem is same as yours.The problem I have is that my parallel_singer don't output the tree file，and I only have files like start with Quercus20_chr8_parallel_singer_0_1*(see picture) ,which is different from the output of singer_master

<img width="1328" alt="Image" src="https://github.com/user-attachments/assets/7213f209-e9e7-4811-8297-abb8d66f9ba7" />

This is my code:
/data/zhangmm/software/SINGER-main/SINGER/SINGER/parallel_singer -Ne 2e5 -m 1.2e-8  -vcf /data/zhangmm/Quercus20_phase/Quercus20_chr8_filtered_phased_addAA -output Quercus20_chr8_parallel_singer -n 100 -thin 20

Error：
 ts = read_long_ARG(node_files, branch_files, mutation_files, block_coordinates)
  File "/data/zhangmm/software/SINGER-main/SINGER/SINGER/convert_long_ARG.py", line 73, in read_long_ARG
    tables.sort()
  File "/data/zhangmm/ENTER/lib/python3.9/site-packages/tskit/tables.py", line 3632, in sort
    self._ll_tables.sort(edge_start, site_start, mutation_start)
_tskit.LibraryError: Sequence length must be > 0. (TSK_ERR_BAD_SEQUENCE_LENGTH)
Traceback (most recent call last):
  File "/data/zhangmm/software/SINGER-main/SINGER/SINGER/convert_long_ARG.py", line 118, in <module>
    main()
  File "/data/zhangmm/software/SINGER-main/SINGER/SINGER/convert_long_ARG.py", line 114, in main
    ts = read_long_ARG(node_files, branch_files, mutation_files, block_coordinates)
  File "/data/zhangmm/software/SINGER-main/SINGER/SINGER/convert_long_ARG.py", line 73, in read_long_ARG
    tables.sort()
  File "/data/zhangmm/ENTER/lib/python3.9/site-packages/tskit/tables.py", line 3632, in sort
    self._ll_tables.sort(edge_start, site_start, mutation_start)
_tskit.LibraryError: Sequence length must be > 0. (TSK_ERR_BAD_SEQUENCE_LENGTH)
Traceback (most recent call last):
  File "/data/zhangmm/software/SINGER-main/SINGER/SINGER/convert_long_ARG.py", line 118, in <module>
    main()
  File "/data/zhangmm/software/SINGER-main/SINGER/SINGER/convert_long_ARG.py", line 114, in main
    ts = read_long_ARG(node_files, branch_files, mutation_files, block_coordinates)
  File "/data/zhangmm/software/SINGER-main/SINGER/SINGER/convert_long_ARG.py", line 73, in read_long_ARG
    tables.sort()
  File "/data/zhangmm/ENTER/lib/python3.9/site-packages/tskit/tables.py", line 3632, in sort
    self._ll_tables.sort(edge_start, site_start, mutation_start)
_tskit.LibraryError: Sequence length must be > 0. (TSK_ERR_BAD_SEQUENCE_LENGTH)
Traceback (most recent call last):
  File "/data/zhangmm/software/SINGER-main/SINGER/SINGER/convert_long_ARG.py", line 118, in <module>
    main()
  File "/data/zhangmm/software/SINGER-main/SINGER/SINGER/convert_long_ARG.py", line 114, in main
    ts = read_long_ARG(node_files, branch_files, mutation_files, block_coordinates)
  File "/data/zhangmm/software/SINGER-main/SINGER/SINGER/convert_long_ARG.py", line 73, in read_long_ARG
    tables.sort()
  File "/data/zhangmm/ENTER/lib/python3.9/site-packages/tskit/tables.py", line 3632, in sort
    self._ll_tables.sort(edge_start, site_start, mutation_start)
_tskit.LibraryError: Sequence length must be > 0. (TSK_ERR_BAD_SEQUENCE_LENGTH)
Traceback (most recent call last):
  File "/data/zhangmm/software/SINGER-main/SINGER/SINGER/convert_long_ARG.py", line 118, in <module>
    main()
  File "/data/zhangmm/software/SINGER-main/SINGER/SINGER/convert_long_ARG.py", line 114, in main
    ts = read_long_ARG(node_files, branch_files, mutation_files, block_coordinates)
  File "/data/zhangmm/software/SINGER-main/SINGER/SINGER/convert_long_ARG.py", line 73, in read_long_ARG
    tables.sort()
  File "/data/zhangmm/ENTER/lib/python3.9/site-packages/tskit/tables.py", line 3632, in sort
    self._ll_tables.sort(edge_start, site_start, mutation_start)
_tskit.LibraryError: Sequence length must be > 0. (TSK_ERR_BAD_SEQUENCE_LENGTH)
Parameters:
Effective population size: 200000.0
Mutation rate: 1.2e-08
Recombination to mutation ratio: 1
Block length: 1000000
VCF file prefix: /data/zhangmm/Quercus20_phase/Quercus20_chr8_filtered_phased_addAA
Output file prefix: Quercus20_chr8_parallel_singer
Number of MCMC samples: 100
Thinning interval length: 20
Site flip probability: 0.5
Tskit conversion freq: 1
Number of cores: 20
Indexing VCF file: /data/zhangmm/Quercus20_phase/Quercus20_chr8_filtered_phased_addAA.vcf with block length: 1000000
['parallel', '-u', '-j', '20', ':::']

**Comment by YunDeng98** [comment]
@zhangming-m thanks for the feedback. It seems that the ARGs have been successfully inferred but the conversion script fails. It should be easy to address. There should be a *.index file somewhere, can you send me a screenshot of that?

**Comment by zhangming-m** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by zhangming-m** [comment]
@YunDeng98  Yes,there is indeed a  Quercus20_chr8_filtered_phased_addAA.index file

<img width="241" alt="Image" src="https://github.com/user-attachments/assets/07770be0-56e2-4234-b551-a9d15c1e3270" />

**Comment by YunDeng98** [comment]
@zhangming-m there is a "convert_long_ARG.py" in the repo which you might want to use. So the usage is like "python convert_long_ARG.py vcf_prefix output_prefix iteration_index". If this does not fix your problem, you can send me the files and I can convert it for you. Just find all the vcf_prefix*_nodes_0.txt, vcf_prefix*_branches_0.txt, vcf_prefix*_muts_0.txt, vcf_prefix*_recombs_0.txt and send them to me. I can work from there.
