### ISSUE TITLE
AssertionError: assert t >= min_time

### ISSUE THREAD

**Issue by hanyoupan** [popgenmethods/SINGER#27]
I'm trying to run parallel_singer on my data. Below is the error message I received.
Would you please take a look? Thanks a lot.

`
in_vcf_path="../vcf/33_rats/06_s300/33_rats_mRatBN7.2_chr19_qual30_bsnp_rmm_rmh_mafgl0_s300"
out_vcf_path="./chr19_s300/chr19_s300"
./singer-0.1.8-beta-linux-x86_64/parallel_singer -Ne 1e4 -m 1.2e-8 -vcf $in_vcf_path -output $out_vcf_path -n 33 -thin 300
`

`
Processing segment 0
Processing segment 1
Traceback (most recent call last):
  File "/mnt/c/hanyou_c/projects/2024-02-21_ancestral_haplotypes_3/singer/singer-0.1.8-beta-linux-x86_64/convert_long_ARG.py", line 118, in <module>
    main()
  File "/mnt/c/hanyou_c/projects/2024-02-21_ancestral_haplotypes_3/singer/singer-0.1.8-beta-linux-x86_64/convert_long_ARG.py", line 114, in main
    ts = read_long_ARG(node_files, branch_files, mutation_files, block_coordinates)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/hanyou_c/projects/2024-02-21_ancestral_haplotypes_3/singer/singer-0.1.8-beta-linux-x86_64/convert_long_ARG.py", line 33, in read_long_ARG
    assert t >= min_time
    ^^^^^^^^^^^^^^^^^^^^
AssertionError
Processing segment 0
Processing segment 1
Traceback (most recent call last):
  File "/mnt/c/hanyou_c/projects/2024-02-21_ancestral_haplotypes_3/singer/singer-0.1.8-beta-linux-x86_64/convert_long_ARG.py", line 118, in <module>
    main()
  File "/mnt/c/hanyou_c/projects/2024-02-21_ancestral_haplotypes_3/singer/singer-0.1.8-beta-linux-x86_64/convert_long_ARG.py", line 114, in main
    ts = read_long_ARG(node_files, branch_files, mutation_files, block_coordinates)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/hanyou_c/projects/2024-02-21_ancestral_haplotypes_3/singer/singer-0.1.8-beta-linux-x86_64/convert_long_ARG.py", line 33, in read_long_ARG
    assert t >= min_time
    ^^^^^^^^^^^^^^^^^^^^
AssertionError
`

![image](https://github.com/user-attachments/assets/0918427b-616d-48fe-b378-fb8222bd2599)

**Comment by hanyoupan** [comment]
[33_rats_mRatBN7.2_chr19_qual30_bsnp_rmm_rmh_mafgl0_s300.txt](https://github.com/user-attachments/files/17722741/33_rats_mRatBN7.2_chr19_qual30_bsnp_rmm_rmh_mafgl0_s300.txt)

**Comment by rosiezhong** [comment]
Hi I'm experiencing the same issue! Any suggestions? @YunDeng98

**Comment by rosiezhong** [comment]
The only work around I could find is cutting down the window size to 50kb
`-L 50000`
